/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asn.sis.gui;

import com.asn.sis.dao.StudentDAO;
import com.asn.sis.dto.StudentDTO;
import java.sql.SQLException;

/**
 *
 * @author Dell
 */
public class AddStudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddStudentPanel
     */
    public AddStudentPanel() {
        initComponents();
        loadDatas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        firstnametxt = new javax.swing.JTextField();
        middlenametxt = new javax.swing.JTextField();
        lastnametxt = new javax.swing.JTextField();
        peraddresstxt = new javax.swing.JTextField();
        tempaddresstxt = new javax.swing.JTextField();
        mobiletxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        parent_nametxt = new javax.swing.JTextField();
        guardian_nametxt = new javax.swing.JTextField();
        parent_contacttxt = new javax.swing.JTextField();
        guardian_contacttxt = new javax.swing.JTextField();
        programtxt = new javax.swing.JTextField();
        semestertxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        sectiontxt = new javax.swing.JTextField();
        malebttn = new javax.swing.JRadioButton();
        femalebttn = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        editBttn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();

        jLabel1.setText("id");

        jLabel2.setText("firstname");

        jLabel3.setText("middlename");

        jLabel4.setText("lastname");

        jLabel5.setText("gender");

        jLabel6.setText("peraddress");

        jLabel7.setText("tempaddress");

        jLabel8.setText("mobile");

        jLabel9.setText("email");

        jLabel10.setText("parents_name");

        jLabel11.setText("guardian_name");

        jLabel12.setText("parents_contact");

        jLabel13.setText("guardian_contact");

        jLabel14.setText("program");

        jLabel15.setText("semester");

        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });
        idtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idtxtFocusLost(evt);
            }
        });
        idtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idtxtKeyReleased(evt);
            }
        });

        firstnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnametxtActionPerformed(evt);
            }
        });
        firstnametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnametxtFocusLost(evt);
            }
        });
        firstnametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstnametxtKeyReleased(evt);
            }
        });

        lastnametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnametxtFocusLost(evt);
            }
        });
        lastnametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastnametxtKeyReleased(evt);
            }
        });

        peraddresstxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                peraddresstxtFocusLost(evt);
            }
        });
        peraddresstxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                peraddresstxtKeyReleased(evt);
            }
        });

        tempaddresstxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempaddresstxtFocusLost(evt);
            }
        });
        tempaddresstxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tempaddresstxtKeyReleased(evt);
            }
        });

        mobiletxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobiletxtFocusLost(evt);
            }
        });
        mobiletxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobiletxtKeyReleased(evt);
            }
        });

        emailtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailtxtFocusLost(evt);
            }
        });
        emailtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailtxtKeyReleased(evt);
            }
        });

        parent_nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parent_nametxtActionPerformed(evt);
            }
        });
        parent_nametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                parent_nametxtFocusLost(evt);
            }
        });
        parent_nametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                parent_nametxtKeyReleased(evt);
            }
        });

        guardian_nametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                guardian_nametxtFocusLost(evt);
            }
        });
        guardian_nametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                guardian_nametxtKeyReleased(evt);
            }
        });

        parent_contacttxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                parent_contacttxtFocusLost(evt);
            }
        });
        parent_contacttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                parent_contacttxtKeyReleased(evt);
            }
        });

        guardian_contacttxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                guardian_contacttxtFocusLost(evt);
            }
        });
        guardian_contacttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                guardian_contacttxtKeyReleased(evt);
            }
        });

        programtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                programtxtFocusLost(evt);
            }
        });
        programtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                programtxtKeyReleased(evt);
            }
        });

        semestertxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                semestertxtFocusLost(evt);
            }
        });
        semestertxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                semestertxtKeyReleased(evt);
            }
        });

        jLabel16.setText("section");

        sectiontxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sectiontxtFocusLost(evt);
            }
        });
        sectiontxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sectiontxtKeyReleased(evt);
            }
        });

        buttonGroup1.add(malebttn);
        malebttn.setText("Male");

        buttonGroup1.add(femalebttn);
        femalebttn.setText("Female");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        editBttn.setText("Edit");
        editBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBttnActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(studentTable);

        errorLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(malebttn)
                                .addGap(18, 18, 18)
                                .addComponent(femalebttn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sectiontxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(semestertxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(programtxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guardian_contacttxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(parent_contacttxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guardian_nametxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(parent_nametxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailtxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mobiletxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tempaddresstxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(peraddresstxt, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(110, 110, 110)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lastnametxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(middlenametxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnametxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idtxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(editBttn)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(190, 190, 190))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {editBttn, jButton1, jButton3, jButton4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(middlenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(malebttn)
                    .addComponent(femalebttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(peraddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tempaddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(mobiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(parent_nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(guardian_nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(parent_contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(guardian_contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(programtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semestertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(sectiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void firstnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnametxtActionPerformed

    private void parent_nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parent_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parent_nametxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         StudentDTO user=new StudentDTO();
        user.setId(Integer.parseInt(idtxt.getText()));
        user.setFirstname(firstnametxt.getText());
        user.setMiddlename(middlenametxt.getText());
        user.setLastname(lastnametxt.getText());
        if(malebttn.isSelected()==true){
          user.setGender("male");  
        }
        if(femalebttn.isSelected()==true){
           user.setGender("female");  
        }
        
        user.setPeraddress(peraddresstxt.getText());
        user.setTempaddress(tempaddresstxt.getText());
        user.setMobile(mobiletxt.getText());
        user.setEmail(emailtxt.getText());
        user.setParent_name(parent_nametxt.getText());
        user.setGuardian_name(guardian_nametxt.getText());
        user.setParent_contact(parent_contacttxt.getText());
        user.setGuardian_contact(guardian_contacttxt.getText());
        user.setProgram(programtxt.getText());
        user.setSemester(semestertxt.getText());
        user.setSection(sectiontxt.getText());
        
        new StudentDAO().addStudent(user);
        clearFields();
        loadDatas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idtxtFocusLost
       if(idtxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            idtxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        }       
    }//GEN-LAST:event_idtxtFocusLost

    private void idtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtKeyReleased
       if(idtxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            idtxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_idtxtKeyReleased

    private void firstnametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnametxtFocusLost
       if(firstnametxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            firstnametxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_firstnametxtFocusLost

    private void firstnametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnametxtKeyReleased
       if(firstnametxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            firstnametxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_firstnametxtKeyReleased

    private void lastnametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnametxtFocusLost
       if(lastnametxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            lastnametxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_lastnametxtFocusLost

    private void lastnametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnametxtKeyReleased
     if(lastnametxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            lastnametxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_lastnametxtKeyReleased

    private void peraddresstxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_peraddresstxtFocusLost
       if(peraddresstxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            peraddresstxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_peraddresstxtFocusLost

    private void peraddresstxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_peraddresstxtKeyReleased
       if(peraddresstxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            peraddresstxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_peraddresstxtKeyReleased

    private void tempaddresstxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempaddresstxtFocusLost
        if(tempaddresstxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            tempaddresstxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_tempaddresstxtFocusLost

    private void tempaddresstxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempaddresstxtKeyReleased
       if(tempaddresstxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            tempaddresstxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_tempaddresstxtKeyReleased

    private void mobiletxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobiletxtFocusLost
        if(mobiletxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            mobiletxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_mobiletxtFocusLost

    private void mobiletxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobiletxtKeyReleased
        if(mobiletxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            mobiletxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_mobiletxtKeyReleased

    private void emailtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtxtFocusLost
       if(emailtxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            emailtxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_emailtxtFocusLost

    private void emailtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailtxtKeyReleased
        if(emailtxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            emailtxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_emailtxtKeyReleased

    private void parent_nametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parent_nametxtFocusLost
        if(parent_nametxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            parent_nametxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_parent_nametxtFocusLost

    private void parent_nametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parent_nametxtKeyReleased
        if(parent_nametxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            parent_nametxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_parent_nametxtKeyReleased

    private void guardian_nametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_guardian_nametxtFocusLost
       if(guardian_nametxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            guardian_nametxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_guardian_nametxtFocusLost

    private void guardian_nametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guardian_nametxtKeyReleased
         if(guardian_nametxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            guardian_nametxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_guardian_nametxtKeyReleased

    private void parent_contacttxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parent_contacttxtFocusLost
         if(parent_contacttxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            parent_contacttxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_parent_contacttxtFocusLost

    private void parent_contacttxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parent_contacttxtKeyReleased
        if(parent_contacttxt.getText().equals("")){
            errorLabel.setText("Email can't be empty");
            parent_contacttxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_parent_contacttxtKeyReleased

    private void guardian_contacttxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_guardian_contacttxtFocusLost
         if(guardian_contacttxt.getText().equals("")){
            errorLabel.setText("Guardian contact can't be empty");
            guardian_contacttxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_guardian_contacttxtFocusLost

    private void guardian_contacttxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guardian_contacttxtKeyReleased
       if(guardian_contacttxt.getText().equals("")){
            errorLabel.setText("Guardian contact can't be empty");
            guardian_contacttxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_guardian_contacttxtKeyReleased

    private void programtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_programtxtFocusLost
        if(programtxt.getText().equals("")){
            errorLabel.setText("Program can't be empty");
            programtxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_programtxtFocusLost

    private void programtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_programtxtKeyReleased
        if(programtxt.getText().equals("")){
            errorLabel.setText("Program can't be empty");
            programtxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_programtxtKeyReleased

    private void semestertxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_semestertxtFocusLost
       if(semestertxt.getText().equals("")){
            errorLabel.setText("Semester can't be empty");
            semestertxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_semestertxtFocusLost

    private void semestertxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semestertxtKeyReleased
       if(semestertxt.getText().equals("")){
            errorLabel.setText("Semester can't be empty");
            semestertxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_semestertxtKeyReleased

    private void sectiontxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sectiontxtFocusLost
      if(sectiontxt.getText().equals("")){
            errorLabel.setText("Section can't be empty");
            sectiontxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_sectiontxtFocusLost

    private void sectiontxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sectiontxtKeyReleased
        if(sectiontxt.getText().equals("")){
            errorLabel.setText("Section can't be empty");
            sectiontxt.requestFocus();
        }
        else{
            errorLabel.setText("");
        } 
    }//GEN-LAST:event_sectiontxtKeyReleased

    private void editBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBttnActionPerformed
     if (editBttn.getText().equalsIgnoreCase("Edit")) {
            editBttn.setText("Update");
            StudentDTO userEdit = new StudentDAO().editStudent(studentTable);
            idtxt.setText(String.valueOf(userEdit.getId()));
            idtxt.setEditable(false);
            firstnametxt.setText(userEdit.getFirstname());
            middlenametxt.setText(userEdit.getMiddlename());
            lastnametxt.setText(userEdit.getLastname());
            peraddresstxt.setText(userEdit.getPeraddress());
            tempaddresstxt.setText(userEdit.getTempaddress());
            mobiletxt.setText(userEdit.getMobile());
            parent_nametxt.setText(userEdit.getParent_name());
            parent_contacttxt.setText(userEdit.getParent_contact());
            guardian_nametxt.setText(userEdit.getGuardian_name());
            guardian_contacttxt.setText(userEdit.getGuardian_contact());
            
            if(userEdit.getGender().equals("male")){
            malebttn.setSelected(true);
            }
            if(femalebttn.isSelected()==true){
            femalebttn.setSelected(true);
            }
            
            emailtxt.setText(userEdit.getEmail());
            sectiontxt.setText(userEdit.getSection());
            semestertxt.setText(userEdit.getSemester());
            
            
            loadDatas();

        } else {

            editBttn.setText("Edit");
            StudentDTO studentUpdate = new StudentDTO();
            studentUpdate.setId(Integer.parseInt(idtxt.getText()));
            
           
            studentUpdate.setFirstname(firstnametxt.getText());
            studentUpdate.setMiddlename(middlenametxt.getText());
            studentUpdate.setLastname(lastnametxt.getText());
            studentUpdate.setGuardian_name(guardian_nametxt.getText());
            studentUpdate.setGuardian_contact(guardian_contacttxt.getText());
            studentUpdate.setParent_name(parent_nametxt.getText());
            studentUpdate.setParent_contact(parent_contacttxt.getText());
            studentUpdate.setSection(sectiontxt.getText());
            studentUpdate.setSemester(semestertxt.getText());
            studentUpdate.setPeraddress(peraddresstxt.getText());
            studentUpdate.setTempaddress(tempaddresstxt.getText());
            studentUpdate.setMobile(mobiletxt.getText());
            studentUpdate.setEmail(emailtxt.getText());
            if(malebttn.isSelected()){
            studentUpdate.setGender("male");
            }
             if(femalebttn.isSelected()){
            studentUpdate.setGender("female");
            }
            
            studentUpdate.setProgram(programtxt.getText());
            new StudentDAO().updateStudent(studentUpdate);
            loadDatas();
            clearFields();
            idtxt.setEditable(true);

        }
    }//GEN-LAST:event_editBttnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         new StudentDAO().deleteStudent(String.valueOf(studentTable.getValueAt(studentTable.getSelectedRow(),0)));//0 means value of first column in the table
       loadDatas();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed
public void clearFields(){
    idtxt.setText("");
    
    firstnametxt.setText("");
    middlenametxt.setText("");
    lastnametxt.setText("");
    if(malebttn.isSelected()==true){ 
        malebttn.setSelected(false);
    }
    if(femalebttn.isSelected()==true){
       femalebttn.setSelected(false);  
    }
   
    peraddresstxt.setText("");
    tempaddresstxt.setText("");
    mobiletxt.setText("");
    emailtxt.setText("");
    parent_nametxt.setText("");
    guardian_nametxt.setText("");
    parent_contacttxt.setText("");
    guardian_contacttxt.setText("");
    programtxt.setText("");
    semestertxt.setText("");
    sectiontxt.setText("");
    
}
public void loadDatas(){
    StudentDAO studentDAO=new StudentDAO();
    try{
    studentTable.setModel(studentDAO.buildTableModel(studentDAO.getQueryResult()));
}catch(SQLException e){
    e.printStackTrace();
}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton editBttn;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JRadioButton femalebttn;
    private javax.swing.JTextField firstnametxt;
    private javax.swing.JTextField guardian_contacttxt;
    private javax.swing.JTextField guardian_nametxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JRadioButton malebttn;
    private javax.swing.JTextField middlenametxt;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JTextField parent_contacttxt;
    private javax.swing.JTextField parent_nametxt;
    private javax.swing.JTextField peraddresstxt;
    private javax.swing.JTextField programtxt;
    private javax.swing.JTextField sectiontxt;
    private javax.swing.JTextField semestertxt;
    private javax.swing.JTable studentTable;
    private javax.swing.JTextField tempaddresstxt;
    // End of variables declaration//GEN-END:variables
}
